### ISSUE TITLE
Remove global config file

### ISSUE THREAD

**Issue by jyecusch** [nitrictech/cli#141]
Move all config that would have lived in the global config file into project-specific config files instead (see: https://github.com/nitrictech/cli/issues/139). This should help improve consistency when teams work on the same project and make it easier to locate the config that's impacting a project.

**Comment by jyecusch** [comment]
This also means removing support for custom command aliases for now, but we can revisit that in future if it's a requested feature.

**Comment by asalkeld** [comment]
done with above PR https://github.com/nitrictech/cli/pull/154
