### ISSUE TITLE
Provide suggestion when stack file is missing

### ISSUE THREAD

**Issue by jyecusch** [nitrictech/cli#144]
If any commands are run which relate to stack, but a stack file isn't present, prompt the user to create a new stack.

commands:

- `nitric stack up`
- `nitric stack down`
- `nitric stack list` _maybe not this one?_
- all aliases of the above (e.g. `nitric up`)

The output should be something like this:

```bash
No stacks were found for the current project. If you haven't created one yet run `nitric stack new`.
```

**Comment by asalkeld** [comment]
done here: https://github.com/nitrictech/cli/blob/develop/pkg/stack/options.go#L53
