### ISSUE TITLE
Catch and prompt to report unexpected errors

### ISSUE THREAD

**Issue by jyecusch** [nitrictech/cli#146]
If someone encounters an unexpected error in the CLI, it would be nice if we could automate or streamline the process to report it to us so we can fix it. Let's look into top-level handling of unexpected errors, print any useful detail from the error and prompt the user to report it.

GitHub provides query params that could help us prefill an issue template, e.g. https://github.com/nitrictech/cli/issues/new?title=foo&body=bar

This shouldn't be done without the CLI user's permission, so let's prompt to report the bug, then open a URL and prefill what we can.

**Comment by raksiv** [comment]
Stacktrace, version of CLI, OS, usual things required for debugging.
