### ISSUE TITLE
Running multiple instances of nitric 

### ISSUE THREAD

**Issue by raksiv** [nitrictech/cli#149]
Can’t run nitric on two different terminals at the same time.

```bash
Local running, use ctrl-C to stop

membrane error, exiting: could not listen on configured service address: listen tcp 0.0.0.0:50051: bind: address already in use
```
 
If the projects have conflicting resource names the error is - 

```bash
ERROR   ContainerCreate: Error response from daemon: Conflict. The container name "/public-api" is already in use by container "b8d736c8a91d4edede1f87658b4bab15a1b08d9a8b4be70d42412fe9219be11a". You have to remove (or rename) that container to be able to reuse that name.
ContainerCreate: Error response from daemon: Conflict. The container name "/event-history" is already in use by container "648e0c68cc09112cd6477d4737f1666b36e9139b226363eecbf34071eb65e63d". You have to remove (or rename) that container to be able to reuse that name. of what the bug is.
```

**Comment by asalkeld** [comment]
@raksiv  is your exception to actually be able to run it twice, or just catch that it is already running and provide a nice message?
Personally don't think it makes sense to have it running twice and in favor of the "nice message".

**Comment by raksiv** [comment]
I've shown the two locations of the errors thrown so that the nice messages can be updated for both.

I think it's a separate issue to support two local instances of Nitric, which is a low-priority enhancement - in most cases people won't want to do this. But if they have accidently done it, then we want to tell them that they can't.

**Comment by raksiv** [comment]
Something along the lines of 

'Error: Only one instance of Nitric can be run locally at a time, please check that you have ended all other instances and try again.'
