### ISSUE TITLE
Feedback command

### ISSUE THREAD

**Issue by jyecusch** [nitrictech/cli#155]
To help devs provide feedback or log an issue a 'feedback' command has been suggested.

```bash
nitric feedback
```

This command should open a pre-filled new GitHub issue page. GitHub providers query params to support issue prefill (see: https://github.com/nitrictech/cli/issues/146).

Should this command prompt for the type of feedback? e.g. issue, feature request?

**Comment by jyecusch** [comment]
We could also consider a feedback survey in the CLI to ask for the type of feedback and offer the survey to anyone who's interested. The main goal here is to capture any issues, suggestions or other feedback people want to provide so we can make the CLI and framework better.

**Comment by raksiv** [comment]
Implement nitric feedback command to open a pre-filled new GitHub issue page. GitHub providers query params to support issue prefill (see: https://github.com/nitrictech/cli/issues/146).

In this version, allow the users to select the type of feedback once they reach the issues page.

**Comment by raksiv** [comment]
Add some information that lets people run a diagnostic to provide the information we need.
They would manually paste it into the issue in the appropriate spot.
