### ISSUE TITLE
The ability to set environment variables for local and deploy

### ISSUE THREAD

**Issue by davemooreuws** [nitrictech/cli#187]
We need an easy way to set environment variables for local run as well as deployment.

**Why is this needed? What challenge will it help you solve? Please describe.**
It is required to test locally and to deploy a working application that uses environment variables

**Describe alternatives you've considered**
including a .env file in the build, not great.

**Comment by asalkeld** [comment]
take note of k8s https://kubernetes.io/docs/tasks/inject-data-application/environment-variable-expose-pod-information/

but the config-as-code version of this might be to:

1. access the project definition (perhaps inserted into a collection,secret or bucket)
2. access the stack outputs (perhaps inserted into a collection,secret or bucket)
3. access environment variables or settings in the nitric.yaml (as a secret)

What do you think @tjholm

**Comment by raksiv** [comment]
Proposal A  - 

Add support for ports for each API locally
Add configurable ports, so that the local user can specify what ports they want to run locally (this might cause port conflict errors with locally running applications)

**Comment by asalkeld** [comment]
I quite like docker compose .env handling https://docs.docker.com/compose/environment-variables/

How this would work:
1. for "nitric run", look for .local and set this in the running container
2. for "nitric up", look for .production and insert into the functions
3. if none are found either can fallback to .env

If --env-file is provided then this overrides the dot file
