### ISSUE TITLE
Ability to run build scripts before docker builds

### ISSUE THREAD

**Issue by asalkeld** [nitrictech/cli#191]
**Describe the solution you'd like**

This could be in the project definition (nitric.yaml)
```yaml
buildScripts:
 - yarn install
```

**Why is this needed? What challenge will it help you solve? Please describe.**

There are often commands needed to be run before a docker build, it would be great to have a mechanism
to say "please run this command before doing the docker build"

**Describe alternatives you've considered**

We have to run this manually and document it.

**Comment by raksiv** [comment]
This requires a conversation before we have anything to action.

**Comment by raksiv** [comment]
Options include exposing a docker file which can be edited
Consider hot-reloading
Might need a convention which can be overwritten

**Comment by raksiv** [comment]
Keeping the docker file hidden with defaults should also be available.

**Comment by tjholm** [comment]
Will be implemented as part of defining custom docker files
