### ISSUE TITLE
Prompt users to provide feedback

### ISSUE THREAD

**Issue by raksiv** [nitrictech/cli#194]
Given we want valuable feedback from users of the Nitric CLI, perhaps we could show a text output after the first use of `nitric new` (or another appropriate command?) which prompts with a message like this:

```
Thanks for trying nitric!

If you have feedback you can raise issues on GitHub https://github.com/nitrictech/nitric or come talk with us directly on Discord https://our.discord.link.example
```

**Comment by raksiv** [comment]
Show it when the user runs Nitric run for the first time, ask me again later?

**Comment by HomelessDinosaur** [comment]
This is blocked until a discord invite link is created.
