### ISSUE TITLE
Default glob matches TypeScript files with JavaScript template

### ISSUE THREAD

**Issue by jyecusch** [nitrictech/cli#197]
Steps:
1. Run `nitric new [name]` to create a project
2. Select the JavaScript template
3. The default glob suggestion is **funtions./*.ts**

```
❯ nitric new jsproj
? Choose a template: official/JavaScript - Starter
? Glob for the function handlers? [tab for suggestions] (functions/*.ts) 
```

The glob suggestion should be based on the template selected, in this case `functions/*.js`

**Comment by jyecusch** [comment]
I know it says 'tab for suggestions' and .js is a suggestion provided, but the default option and the list of suggestions should be template-specific.

It should probably go as far as being baked into the template (don't provide the prompt at all). Picking the wrong option here would cause the template code not to run. Also, before you've looked at the template, how would you know what glob patterns will work with it?

**Comment by tjholm** [comment]
This should definitely be baked into the template. We can always read the original yaml file and re-write properties like the project name after copying the template

**Comment by raksiv** [comment]
Yeh, putting this into the template is a good improvement to the dx. 
The setting only needs editing by more advanced users.
