### ISSUE TITLE
`up` cmd prints a confusing error message when a stack name isn't provided

### ISSUE THREAD

**Issue by jyecusch** [nitrictech/cli#221]
**Describe the bug**
`nitric up` prints a confusing error message when a stack name isn't provided. If I have a 'dev' stack file `nitric-dev.yaml` and run the up command without the stack flag it prints this error:

```bash
nitric up
Error: no nitric stack found (unable to find nitric-.yaml). If you haven't created a stack yet, run `nitric stack new` to get started
```

**Expected behavior**
If there is only one stack then `nitric up` without the `-s` flag should choose it by default. If there is more than one it should prompt to choose one.

**To Reproduce**

1. Create a new nitric project
2. Run `nitric stack new` to create a new stack
3. Run `nitric up` (don't provide the `-s` flag)

**Comment by asalkeld** [comment]
In the develop branch the output is

```
Error: required flag(s) "stack" not set
Usage:
  nitric stack update [-s stack] [flags]

Aliases:
  update, up

Examples:
nitric stack update -s aws

```
