### ISSUE TITLE
Topic names are not auto-named in aws - this causes conflicts when two projects have the same topic name.

### ISSUE THREAD

**Issue by raksiv** [nitrictech/cli#289]
Attaching a snippet of code which explains why topics are not auto-named.
This might require an additional issue to resolve - 

	for k := range a.proj.Topics {
		a.topics[k], err = sns.NewTopic(ctx, k, &sns.TopicArgs{
			// FIXME: Autonaming of topics disabled until improvements to
			// nitric topic name discovery is made for SNS topics.
			Name: pulumi.StringPtr(k),
			Tags: common.Tags(ctx, k),
		})
		if err != nil {
			return errors.WithMessage(err, "sns topic "+k)
		}
	}

**Comment by asalkeld** [comment]
https://github.com/nitrictech/cli/blob/develop/pkg/provider/pulumi/aws/aws.go#L194-L204
