### ISSUE TITLE
Support install scripts

### ISSUE THREAD

**Issue by jyecusch** [nitrictech/cli#297]
Cloning templates, like the JavaScript template, then using `nitric run` or `nitric up` result in errors since no `package.lock` or `yarn.lock` exists. Extending `nitric.yaml` to support commands that enable scripts to be run prior to a build could fix this issue for new users.

**Comment by jyecusch** [comment]
How does Vercel handle this for sample project cloning? Do they contain a lock file, does the Vercel platform add one?

**Comment by tjholm** [comment]
I think the solution provided here is too broad for the specific issue. We do need more customisation and extensibility, but I would rescope this issue to specifically handling how we deal with *.lock files for node projects.

**Comment by asalkeld** [comment]
can we not add this logic into the typescript runtime?

**Comment by tjholm** [comment]
Supported with custom dockerfile support
