### ISSUE TITLE
Local development dashboard

### ISSUE THREAD

**Issue by tjholm** [nitrictech/cli#463]
Create a local dashboard for local dev experience when using the `start` or `run` commands. The dashboard can reuse assets from Nitric Deploy such as the stack graph/components as well as features to assist with local testing such as a simple REST client.

The UI should automatically refresh with updated resources, APIs etc. as code is changed. Consider websockets or similar for this.

**Comment by davemooreuws** [comment]
Brain dump:
Serve a static Astro site from the CLI. Which has hydrated components (islands) for retrieving resources etc.

**Comment by tjholm** [comment]
@davemooreuws sounds good to me, we'll directly embed the static output using `embed.FS` and serve it directly from the same endpoint that serves the API that will back the dashboard.

**Comment by davemooreuws** [comment]
We will also need an API to dynamically communicate between CLI and dashboard.

**Comment by tjholm** [comment]
Close as done with shell complete in:
https://github.com/nitrictech/cli/pull/464

Rest to be done in additional issues.
