### ISSUE TITLE
Improve the output of the `stack new` command

### ISSUE THREAD

**Issue by jyecusch** [nitrictech/cli#568]
The current output is inconsistent, the output has mixed letter casing and while the provider says "which do you wish.." the region said "select" when they're both dropdown selections. I think we could make some small changes to improve this output.

Current:

```
nitric stack new
? What do you want to call your new stack? dev
? Which Cloud do you wish to deploy to? aws
? select the region us-east-1
```

Suggest updating to something consistent:

```
nitric stack new
? What do you want to name this stack? dev
? Which provider do you want to deploy with? aws
? Which region should the stack deploy to? us-east-1
```

or something concise:

```
nitric stack new
? Stack name: dev
? Provider: aws
? Region: us-east-1
```

**Comment by jyecusch** [comment]
Once we decide and implement this we should update relevant docs/examples where we can.

**Comment by davemooreuws** [comment]
Closing as duplicate of https://github.com/nitrictech/nitric/issues/506
